# Copyright (c) Meta Platforms, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Verax C++ CI

on:
  push:
    branches: [main]
    paths:
      - 'logical_plan/**'
      - 'optimizer/**'
      - 'public_tld/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [main]
    paths:
      - 'logical_plan/**'
      - 'optimizer/**'
      - 'public_tld/**'
      - '.github/workflows/test.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Install pre-commit
        run: python -m pip install pre-commit

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          persist-credentials: false

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-

      - name: Run pre-commit
        run: |
          files=$(git diff --name-only HEAD^1 HEAD)
          echo "::group::Changed files"
          echo $files | tr ' ' '\n'
          echo "::endgroup::"
          pre-commit run --show-diff-on-failure --color=always --files $files

  build-and-test:
    runs-on: ubuntu-latest
    needs: pre-commit
    env:
      CPU_TARGET: "default"
      CCACHE_DIR: ${{ github.workspace }}/ccache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: 'recursive'

      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-ubuntu-${{ hashFiles('CMakeLists.txt', 'logical_plan/**/*.cpp', 'logical_plan/**/*.h', 'optimizer/**/*.cpp', 'optimizer/**/*.h') }}
          restore-keys: |
            ccache-ubuntu-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential ccache libboost-all-dev libgtest-dev libgoogle-glog-dev libgflags-dev libfolly-dev

      - name: Zero ccache statistics
        run: ccache -z

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build build --config Release -j $(nproc)

      - name: Show ccache statistics
        run: ccache -s

      - name: Run tests
        run: ctest --test-dir build --output-on-failure -j $(nproc)
